version: '3.8'
services:
  db:
    container_name: php54-mysql56-db
    image: mysql:5.6
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "33306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  web:
    container_name: php54-mysql56-web
    depends_on:
      - db
    build: docker/web
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    restart: always

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8889:8025"

volumes:
  db-data:
    driver: local

